"""add_is_ontime_to_recruitment_data

Revision ID: c546413d43d6
Revises: be2fe3fceb46
Create Date: 2026-02-25 13:14:06.344738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c546413d43d6'
down_revision: Union[str, Sequence[str], None] = 'be2fe3fceb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruitment_data', sa.Column('is_ontime', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruitment_data', 'is_ontime')
    # ### end Alembic commands ###
